# Generated by Django 4.2.16 on 2024-09-17 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('satisfaction', models.IntegerField()),
            ],
        ),
    ]
